[project]
name = "slack-migration-watcher"
version = "0.1.0"
description = "Prometheus metrics exporter for anything"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "prometheus-client>=0.22.1",
    "requests>=2.32.5",
]
